# Configurazione del Trading System

simulator:
  initial_capital: 10000  # Capitale iniziale per il trading
  min_candles: 50        # Numero minimo di candele necessarie per gli indicatori
  data_file: "market_data_BTC_1m.csv"  # Nome del file dati da utilizzare

trading:
  position:
    size_pct: 5          # Percentuale del capitale per posizione
    stop_loss_pct: 2.0   # Percentuale stop loss
    take_profit_pct: 4.0 # Percentuale take profit
  
  indicators:
    entry:
      indicator1:
        type: "SMA"
        params:
          timeperiod: 20
      indicator2:
        type: "SMA"
        params:
          timeperiod: 50
      operator: "cross_above"  # Possibili valori: ">", "<", "cross_above", "cross_below"
    
    exit:
      indicator1:
        type: "RSI"
        params:
          timeperiod: 14
      indicator2:
        type: "CLOSE"
        params: {}
      operator: ">"

  # Parametri per i geni specializzati
  volatility_gene:
    enabled: true
    parameters:
      timeperiod:
        min: 10
        max: 50
        default: 14
      multiplier:
        min: 0.5
        max: 2.0
        default: 1.0
      base_position_size:
        min: 1.0
        max: 10.0
        default: 5.0
      atr_limits:
        min_size: 1.0
        max_size: 20.0

  momentum_gene:
    enabled: true
    parameters:
      momentum_threshold:
        min: 60
        max: 80
        default: 70
      trend_strength:
        min: 20
        max: 30
        default: 25
      overbought_level:
        min: 75
        max: 85
        default: 80
      oversold_level:
        min: 15
        max: 25
        default: 20
      rsi:
        timeperiod: 14
      stochastic:
        fastk_period: 14
        slowk_period: 3
        slowd_period: 3
      adx:
        timeperiod: 14

  pattern_gene:
    enabled: true
    parameters:
      required_patterns:
        min: 1
        max: 3
        default: 2
      pattern_window:
        min: 2
        max: 5
        default: 3
      confirmation_periods:
        min: 1
        max: 3
        default: 1
    patterns:
      - ENGULFING
      - HAMMER
      - DOJI
      - EVENINGSTAR
      - MORNINGSTAR
      - HARAMI
      - SHOOTINGSTAR
      - MARUBOZU

genetic:
  population_size: 300     # Aumentato
  generations: 100         # Aumentato
  mutation_rate: 0.2      # Aumentato per maggiore esplorazione
  elite_size: 5           # Ridotto
  tournament_size: 5      # Ridotto per minore pressione selettiva
  min_trades: 50          # Aumentato per maggiore robustezza
  parallel_processes: 10  # Parallelizzazione
  batch_size: 32         # Dimensione batch
  
  optimizer:
    use_gpu: false       # Usa GPU se disponibile
    torch_threads: -1    # -1 usa tutti i thread disponibili
    batch_norm: true     # Usa batch normalization
    precision: "float32" # Può essere "float32" o "float16"

  # Pesi per l'ensemble di geni
  ensemble_weights:
    base_gene: 0.4
    volatility_gene: 0.2
    momentum_gene: 0.2
    pattern_gene: 0.2

  fitness_weights:
    profit_score:
      total_pnl: 0.4
      max_drawdown: 0.3
      sharpe_ratio: 0.3
    quality_score:
      win_rate: 0.6
      trade_frequency: 0.4
    final_weights:
      profit: 0.6
      quality: 0.4

download:
  symbol: "BTCUSDT"
  interval: "1m"
  start_date: "2024-11-25"
  end_date: null
  batch_size: 1000
  output_folder: "data"
  api:
    key: ""
    secret: ""