# Configurazione bilanciata per evitare overflow risorse

simulator:
  initial_capital: 10000
  min_candles: 50
  data_file: "market_data_BTC_1m.csv"

trading:
  position:
    size_pct: 5
    stop_loss_pct: 2.0
    take_profit_pct: 4.0
  
  indicators:
    entry:
      indicator1:
        type: "SMA"
        params:
          timeperiod: 20
      indicator2:
        type: "SMA"
        params:
          timeperiod: 50
      operator: "cross_above"

    exit:
      indicator1:
        type: "RSI"
        params:
          timeperiod: 14
      indicator2:
        type: "CLOSE"
        params: {}
      operator: ">"

  volatility_gene:
    enabled: true
    parameters:
      timeperiod:
        min: 5    
        max: 100  
        default: 14
      multiplier:
        min: 0.3  
        max: 3.0  
        default: 1.0
      base_position_size:
        min: 0.5  
        max: 15.0 
        default: 5.0
      atr_limits:
        min_size: 0.5
        max_size: 25.0

  momentum_gene:
    enabled: true
    parameters:
      momentum_threshold:
        min: 50
        max: 90
        default: 70
      trend_strength:
        min: 15
        max: 35
        default: 25
      overbought_level:
        min: 70
        max: 90
        default: 80
      oversold_level:
        min: 10
        max: 30
        default: 20
      rsi:
        timeperiod: 14
      stochastic:
        fastk_period: 14
        slowk_period: 3
        slowd_period: 3
      adx:
        timeperiod: 14

  pattern_gene:
    enabled: true
    parameters:
      required_patterns:
        min: 1
        max: 4
        default: 2
      pattern_window:
        min: 2
        max: 7
        default: 3
      confirmation_periods:
        min: 1
        max: 4
        default: 1
    patterns:
      - ENGULFING
      - HAMMER
      - DOJI
      - EVENINGSTAR
      - MORNINGSTAR
      - HARAMI
      - SHOOTINGSTAR
      - MARUBOZU

# Configurazione ottimizzata per CPU i7 1551H

genetic:
  # Parametri base bilanciati
  population_size: 480       # Ridotto (480 = 12 * 40)
  generations: 150           # Mantenuto per risultati di qualità
  mutation_rate: 0.38
  elite_size: 3
  tournament_size: 3
  min_trades: 50
  parallel_processes: 12     # Ridotto per gestire meglio la memoria
  batch_size: 40            # Aumentato per efficienza CPU/memoria
  
  # Parametri di gestione plateau
  mutation_decay: 0.988
  diversity_threshold: 0.18
  restart_threshold: 15
  improvement_threshold: 0.002
  restart_elite_fraction: 0.12
  restart_mutation_multiplier: 2.2

  optimizer:
    use_gpu: false
    torch_threads: 16       # Ridotto per bilanciare CPU/memoria
    batch_norm: true
    precision: "float32"


  ensemble_weights:
    base_gene: 0.3
    volatility_gene: 0.25
    momentum_gene: 0.25
    pattern_gene: 0.2

  # Pesi fitness
  fitness_weights:
    profit_score:
      total_pnl: 0.35
      max_drawdown: 0.35
      sharpe_ratio: 0.30
    quality_score:
      win_rate: 0.45
      trade_frequency: 0.35
      consistency: 0.20
    final_weights:
      profit: 0.50
      quality: 0.40
      diversity: 0.10

download:
  symbol: "BTCUSDT"
  interval: "1m"
  start_date: "2024-11-25"
  end_date: null
  batch_size: 1000
  output_folder: "data"
  api:
    key: ""
    secret: ""