simulator:
  initial_capital: 10000
  min_candles: 50
  data_file: "market_data_LUNC_1m"
  metrics:
    returns_limit: 10.0
    min_equity: 1e-6
    annualization_factor: 252
    element_size_bytes: 32

system:
  environment_check:
    hugepages:
      min_count: 64
    memory:
      min_total_gb: 12
      min_available_gb: 4
    gpu:
      command_timeout_sec: 15
  
  process:
    linux:
      nice_high: -5
      nice_low: 10
      oom_score: 1000
    memory:
      gpu_reserve_pct: 0.25
      ram_reserve_pct: 0.35
    batch:
      max_size: 2048
      default_size: 16
      fallback_size: 8
    workers:
      max_count: 8
      reserved_cores: 1

trading:
  position:
    size_pct: 40
    stop_loss_pct: 1.5
    take_profit_pct: 3.0

  indicators:
    entry:
      indicator1:
        type: "EMA"
        params:
          timeperiod: 15
      indicator2:
        type: "EMA"
        params:
          timeperiod: 40
      operator: "cross_above"

    exit:
      indicator1:
        type: "RSI"
        params:
          timeperiod: 12
      indicator2:
        type: "CLOSE"
        params: {}
      operator: ">"

    parameters:
      bollinger:
        num_std: 2.2
      rsi:
        epsilon: 1e-10
        scale: 100.0
      macd:
        fast_period: 10
        slow_period: 22
        signal_period: 7
      ema:
        alpha_multiplier: 2.2
      ranges:
        timeperiod:
          min: 4
          max: 40
        fast_period:
          min: 4
          max: 16
        slow_period:
          min: 12
          max: 32
        signal_period:
          min: 4
          max: 12

  volatility_gene:
    enabled: true
    parameters:
      timeperiod:
        min: 4
        max: 80
        default: 12
      multiplier:
        min: 0.3
        max: 2.0
        default: 0.8
      base_position_size:
        min: 0.4
        max: 12.0
        default: 4.0
      atr_limits:
        min_size: 0.4
        max_size: 20.0

genetic:
  population_size: 120
  generations: 75
  mutation_rate: 0.55
  elite_size: 2
  tournament_size: 6
  min_trades: 200
  batch_size: 12

  optimizer:
    gpu_backend: "auto"  # auto, cuda, arc, cpu
    use_gpu: true
    torch_threads: 8
    device_config:
      cuda:
        enabled: true
        precision: "float32"
        memory_reserve: 2048
        mixed_precision: true
        max_batch_size: 131072
        memory_strategy:
          preallocate: true
          prealloc_threshold: 0.4
          empty_cache_threshold: 0.8
          force_release_threshold: 0.9
      arc:
        enabled: true
        precision: "float16"
        memory_reserve: 1024
        mixed_precision: true
        max_batch_size: 65536
        memory_strategy:
          preallocate: true
          prealloc_threshold: 0.3
          empty_cache_threshold: 0.7
          force_release_threshold: 0.8
    
    cuda_config:
      optimization_level: 3
      allow_tf32: true
      benchmark: true
      deterministic: false

  momentum_gene:
    enabled: true
    parameters:
      momentum_threshold:
        min: 45
        max: 85
        default: 65
      trend_strength:
        min: 12
        max: 30
        default: 20
      overbought_level:
        min: 65
        max: 85
        default: 75
      oversold_level:
        min: 15
        max: 35
        default: 25
      rsi:
        timeperiod: 12
      stochastic:
        fastk_period: 12
        slowk_period: 2
        slowd_period: 2
      adx:
        timeperiod: 12

  pattern_gene:
    enabled: true
    parameters:
      required_patterns:
        min: 1
        max: 3
        default: 2
      pattern_window:
        min: 2
        max: 5
        default: 3
      confirmation_periods:
        min: 1
        max: 3
        default: 1
    patterns:
      - ENGULFING
      - HAMMER
      - DOJI
      - EVENINGSTAR
      - MORNINGSTAR
      - HARAMI

  mutation_decay: 0.985
  diversity_threshold: 0.35
  restart_threshold: 6
  improvement_threshold: 0.003
  restart_elite_fraction: 0.15
  restart_mutation_multiplier: 2.0

  diversity:
    top_performer_threshold: 0.75
    performance_bonus_limit: 0.15
    performance_bonus_multiplier: 0.25
    injection_fraction: 0.3

  reproduction:
    crossover_probability: 0.75
    strong_mutation_multiplier: 1.8
    max_attempts_multiplier: 2.5

  memory_management:
    preallocation: true
    cache_mode: "balanced"
    release_threshold: 0.8
    defrag_threshold: 0.6
    periodic_gc: true
    gc_interval: 90

  parallel_config:
    chunk_size: 128
    cuda_streams: 2
    async_loading: true
    pin_memory: true
    persistent_workers: true

  ensemble_weights:
    base_gene: 0.25
    volatility_gene: 0.3
    momentum_gene: 0.3
    pattern_gene: 0.15

  fitness_weights:
    profit_score:
      total_pnl: 0.3
      max_drawdown: 0.3
      sharpe_ratio: 0.4
    quality_score:
      win_rate: 0.4
      trade_frequency: 0.3
      consistency: 0.3
    final_weights:
      profit: 0.45
      quality: 0.4
      diversity: 0.15
    penalties:
      max_trades:
        limit: 400
        penalty: 0.7
      max_drawdown:
        limit: 0.25
        penalty: 0.8
      min_win_rate:
        limit: 0.45
        penalty: 0.95

download:
  symbol: "LUNCUSDT"
  interval: "1m"
  start_date: "2023-06-01"
  end_date: null
  batch_size: 1000
  output_folder: "data"
  api:
    key: ""
    secret: ""
