simulator:
  initial_capital: 10000
  min_candles: 50
  data_file: "market_data_LUNC_1m"
  metrics:
    returns_limit: 10.0
    min_equity: 1e-6
    annualization_factor: 252
    element_size_bytes: 32

system:
  environment_check:
    hugepages:
      min_count: 64
    memory:
      min_total_gb: 12
      min_available_gb: 4
    gpu:
      command_timeout_sec: 15
  
  process:
    linux:
      nice_high: -5
      nice_low: 10
      oom_score: 1000
    memory:
      gpu_reserve_pct: 0.25  # Ridotto da 0.3
      ram_reserve_pct: 0.35  # Ridotto da 0.4
    batch:
      max_size: 2048  # Ridotto da 4096
      default_size: 16  # Ridotto da 32
      fallback_size: 8  # Ridotto da 16
    workers:
      max_count: 8  # Ridotto da 12
      reserved_cores: 1  # Ridotto da 2

trading:
  position:
    size_pct: 40  # Ridotto da 50 per maggior cautela
    stop_loss_pct: 1.5  # Ridotto da 2.0
    take_profit_pct: 3.0  # Ridotto da 4.0

  indicators:
    entry:
      indicator1:
        type: "EMA"  # Cambiato da SMA a EMA
        params:
          timeperiod: 15  # Ridotto da 20
      indicator2:
        type: "EMA"  # Cambiato da SMA a EMA
        params:
          timeperiod: 40  # Ridotto da 50
      operator: "cross_above"

    exit:
      indicator1:
        type: "RSI"
        params:
          timeperiod: 12  # Ridotto da 14
      indicator2:
        type: "CLOSE"
        params: {}
      operator: ">"

    parameters:
      bollinger:
        num_std: 2.2  # Aumentato da 2.0
      rsi:
        epsilon: 1e-10
        scale: 100.0
      macd:
        fast_period: 10  # Ridotto da 12
        slow_period: 22  # Ridotto da 26
        signal_period: 7  # Ridotto da 9
      ema:
        alpha_multiplier: 2.2  # Aumentato da 2.0
      ranges:
        timeperiod:
          min: 4  # Ridotto da 5
          max: 40  # Ridotto da 50
        fast_period:
          min: 4  # Ridotto da 5
          max: 16  # Ridotto da 20
        slow_period:
          min: 12  # Ridotto da 15
          max: 32  # Ridotto da 40
        signal_period:
          min: 4  # Ridotto da 5
          max: 12  # Ridotto da 15

  volatility_gene:
    enabled: true
    parameters:
      timeperiod:
        min: 4  # Ridotto da 5
        max: 80  # Ridotto da 100
        default: 12  # Ridotto da 14
      multiplier:
        min: 0.3  # Ridotto da 0.4
        max: 2.0  # Ridotto da 2.5
        default: 0.8  # Ridotto da 1.0
      base_position_size:
        min: 0.4  # Ridotto da 0.5
        max: 12.0  # Ridotto da 15.0
        default: 4.0  # Ridotto da 5.0
      atr_limits:
        min_size: 0.4  # Ridotto da 0.5
        max_size: 20.0  # Ridotto da 25.0

genetic:
  population_size: 120
  generations: 75
  mutation_rate: 0.55
  elite_size: 2
  tournament_size: 6
  min_trades: 200
  batch_size: 12

  optimizer:
    gpu_backend: "auto"  # auto, cuda, arc, cpu
    use_gpu: false
    torch_threads: 8
    device_config:
      cuda:
        enabled: true
        precision: "float32"
        memory_reserve: 2048
        mixed_precision: true
        max_batch_size: 131072
        memory_strategy:
          preallocate: true
          prealloc_threshold: 0.4
          empty_cache_threshold: 0.8
          force_release_threshold: 0.9
      arc:
        enabled: true
        precision: "float16"
        memory_reserve: 1024
        mixed_precision: true
        max_batch_size: 65536
        memory_strategy:
          preallocate: true
          prealloc_threshold: 0.3
          empty_cache_threshold: 0.7
          force_release_threshold: 0.8
    
    cuda_config:
      optimization_level: 3
      allow_tf32: true
      benchmark: true
      deterministic: false

  momentum_gene:
    enabled: true
    parameters:
      momentum_threshold:
        min: 45  # Ridotto da 50
        max: 85  # Ridotto da 90
        default: 65  # Ridotto da 70
      trend_strength:
        min: 12  # Ridotto da 15
        max: 30  # Ridotto da 35
        default: 20  # Ridotto da 25
      overbought_level:
        min: 65  # Ridotto da 70
        max: 85  # Ridotto da 90
        default: 75  # Ridotto da 80
      oversold_level:
        min: 15  # Aumentato da 10
        max: 35  # Aumentato da 30
        default: 25  # Aumentato da 20
      rsi:
        timeperiod: 12  # Ridotto da 14
      stochastic:
        fastk_period: 12  # Ridotto da 14
        slowk_period: 2  # Ridotto da 3
        slowd_period: 2  # Ridotto da 3
      adx:
        timeperiod: 12  # Ridotto da 14

  pattern_gene:
    enabled: true
    parameters:
      required_patterns:
        min: 1
        max: 3  # Ridotto da 4
        default: 2
      pattern_window:
        min: 2
        max: 5  # Ridotto da 7
        default: 3
      confirmation_periods:
        min: 1
        max: 3  # Ridotto da 4
        default: 1
    patterns:
      - ENGULFING
      - HAMMER
      - DOJI
      - EVENINGSTAR
      - MORNINGSTAR
      - HARAMI

  # Parametri evolutivi ottimizzati
  mutation_decay: 0.985  # Ridotto da 0.995
  diversity_threshold: 0.35  # Aumentato da 0.25
  restart_threshold: 6  # Ridotto da 8
  improvement_threshold: 0.003  # Aumentato da 0.002
  restart_elite_fraction: 0.15  # Aumentato da 0.12
  restart_mutation_multiplier: 2.0  # Ridotto da 2.2

  # Parametri diversità ottimizzati
  diversity:
    top_performer_threshold: 0.75  # Ridotto da 0.8
    performance_bonus_limit: 0.15  # Aumentato da 0.1
    performance_bonus_multiplier: 0.25  # Aumentato da 0.2
    injection_fraction: 0.3  # Aumentato da 0.2

  # Parametri riproduzione ottimizzati
  reproduction:
    crossover_probability: 0.75  # Ridotto da 0.85
    strong_mutation_multiplier: 1.8  # Aumentato da 1.5
    max_attempts_multiplier: 2.5  # Aumentato da 2.0

  # Monitoraggio performance ottimizzato
  performance_monitoring:
    enabled: true
    metrics_interval: 4  # Aumentato da 2
    memory_warnings: true
    threshold_utilization: 0.9  # Aumentato da 0.85

  # Batch processing ottimizzato
  batch_processing:
    enabled: true
    adaptive_batching: true
    min_batch_size: 65536  # Ridotto da 131072
    max_batch_size: 131072  # Ridotto da 262144
    memory_limit: 3072  # Ridotto da 4096
    prefetch_factor: 2  # Ridotto da 3
    overlap_transfers: true  # Cambiato da false

  # Gestione memoria ottimizzata
  memory_management:
    preallocation: true
    cache_mode: "balanced"  # Cambiato per bilanciare prestazioni e memoria
    release_threshold: 0.8  # Ridotto per liberare memoria più spesso
    defrag_threshold: 0.6  # Ridotto per deframmentare più spesso
    periodic_gc: true
    gc_interval: 90  # Ridotto per pulizia più frequente

  # Configurazione parallela ottimizzata
  parallel_config:
    chunk_size: 128  # Ridotto da 256
    cuda_streams: 2  # Aumentato da 1
    async_loading: true
    pin_memory: true  # Cambiato da false
    persistent_workers: true  # Cambiato da false

  ensemble_weights:
    base_gene: 0.25  # Ridotto da 0.3
    volatility_gene: 0.3  # Aumentato da 0.25
    momentum_gene: 0.3  # Aumentato da 0.25
    pattern_gene: 0.15  # Ridotto da 0.2

  fitness_weights:
    profit_score:
      total_pnl: 0.3  # Ridotto da 0.35
      max_drawdown: 0.3  # Aumentato da 0.25
      sharpe_ratio: 0.4
    quality_score:
      win_rate: 0.4  # Ridotto da 0.45
      trade_frequency: 0.3  # Aumentato da 0.25
      consistency: 0.3
    final_weights:
      profit: 0.45  # Ridotto da 0.50
      quality: 0.4
      diversity: 0.15  # Aumentato da 0.10
    penalties:
      max_trades:
        limit: 400  # Ridotto da 500
        penalty: 0.7  # Ridotto da 0.8
      max_drawdown:
        limit: 0.25  # Ridotto da 0.3
        penalty: 0.8  # Aumentato da 0.7
      min_win_rate:
        limit: 0.45  # Aumentato da 0.4
        penalty: 0.95  # Aumentato da 0.9

download:
  symbol: "LUNCUSDT"
  interval: "1m"
  start_date: "2023-06-01"
  end_date: null
  batch_size: 1000  
  output_folder: "data"
  api:
    key: ""
    secret: ""