simulator:
  initial_capital: 10000
  min_candles: 50
  data_file: "market_data_BTC_1m"
  metrics:
    returns_limit: 10.0
    min_equity: 1e-6
    annualization_factor: 252
    element_size_bytes: 32

system:
  environment_check:
    hugepages:
      min_count: 32
    memory:
      min_total_gb: 8
      min_available_gb: 3
    gpu:
      command_timeout_sec: 10
  
  process:
    linux:
      nice_high: -10
      nice_low: 5
      oom_score: 800
    memory:
      gpu_reserve_pct: 0.20
      ram_reserve_pct: 0.25
    batch:
      max_size: 1024
      default_size: 8
      fallback_size: 4
    workers:
      max_count: 12
      reserved_cores: 2

trading:
  position:
    size_pct: 40
    stop_loss_pct: 1.5
    take_profit_pct: 3.0

  indicators:
    entry:
      indicator1:
        type: "EMA"
        params:
          timeperiod: 15
      indicator2:
        type: "EMA"
        params:
          timeperiod: 40
      operator: "cross_above"

    exit:
      indicator1:
        type: "RSI"
        params:
          timeperiod: 12
      indicator2:
        type: "CLOSE"
        params: {}
      operator: ">"

    parameters:
      bollinger:
        num_std: 2.2
      rsi:
        epsilon: 1e-10
        scale: 100.0
      macd:
        fast_period: 10
        slow_period: 22
        signal_period: 7
      ema:
        alpha_multiplier: 2.2
      ranges:
        timeperiod:
          min: 4
          max: 40
        fast_period:
          min: 4
          max: 16
        slow_period:
          min: 12
          max: 32
        signal_period:
          min: 4
          max: 12

  volatility_gene:
    enabled: true
    parameters:
      timeperiod:
        min: 4
        max: 80
        default: 12
      multiplier:
        min: 0.3
        max: 2.0
        default: 0.8
      base_position_size:
        min: 0.4
        max: 12.0
        default: 4.0
      atr_limits:
        min_size: 0.4
        max_size: 20.0

genetic:
  population_size: 80
  generations: 75
  mutation_rate: 0.55
  elite_size: 2
  tournament_size: 4
  min_trades: 150
  batch_size: 16384

  optimizer:
    gpu_backend: "arc"
    use_gpu: true
    torch_threads: 6
    device_config:
      precision: "float32"
      cuda:
        enabled: false
      arc:
        enabled: true
        precision: "float32"
        memory_reserve: 2048
        mixed_precision: true
        max_batch_size: 32768
        memory_strategy:
          preallocate: false  # Disabilitato per evitare conflitti
          prealloc_threshold: 0.4
          empty_cache_threshold: 0.85  # Aumentato
          force_release_threshold: 0.95  # Aumentato
    
    cuda_config:
      optimization_level: 3
      allow_tf32: false
      benchmark: true
      deterministic: false

  batch_processing:
    enabled: true
    adaptive_batching: true
    min_batch_size: 8192
    max_batch_size: 32768
    memory_limit: 2048
    prefetch_factor: 1  # Ridotto per minor consumo memoria
    overlap_transfers: false  # Disabilitato per evitare conflitti

  parallel_config:
    chunk_size: 128
    cuda_streams: 0
    xpu_streams: 1
    async_loading: false  # Disabilitato per evitare conflitti
    pin_memory: true
    persistent_workers: true

  performance_monitoring:
    enabled: true
    metrics_interval: 1
    memory_warnings: true
    threshold_utilization: 0.85

  adaptive_mutation:
    enabled: true
    initial_rate: 0.55
    min_rate: 0.1
    max_rate: 0.8
    adaptation_speed: 0.1
    fitness_threshold: 0.6
    stagnation_threshold: 5
    reset_threshold: 10
    diversity_weight: 0.3

  momentum_gene:
    enabled: true
    parameters:
      momentum_threshold:
        min: 45
        max: 85
        default: 65
      trend_strength:
        min: 12
        max: 30
        default: 20
      overbought_level:
        min: 65
        max: 85
        default: 75
      oversold_level:
        min: 15
        max: 35
        default: 25
      rsi:
        timeperiod: 12
      stochastic:
        fastk_period: 12
        slowk_period: 2
        slowd_period: 2
      adx:
        timeperiod: 12

  pattern_gene:
    enabled: true
    parameters:
      required_patterns:
        min: 1
        max: 3
        default: 2
      pattern_window:
        min: 2
        max: 5
        default: 3
      confirmation_periods:
        min: 1
        max: 3
        default: 1
    patterns:
      - ENGULFING
      - HAMMER
      - DOJI
      - EVENINGSTAR
      - MORNINGSTAR
      - HARAMI

  mutation_decay: 0.985
  diversity_threshold: 0.35
  restart_threshold: 6
  improvement_threshold: 0.003
  restart_elite_fraction: 0.15
  restart_mutation_multiplier: 2.0

  diversity:
    top_performer_threshold: 0.75
    performance_bonus_limit: 0.15
    performance_bonus_multiplier: 0.25
    injection_fraction: 0.3

  reproduction:
    crossover_probability: 0.75
    strong_mutation_multiplier: 1.8
    max_attempts_multiplier: 2.5

  memory_management:
    preallocation: false  # Disabilitato per evitare conflitti
    cache_mode: "conservative"  # Cambiato da balanced a conservative
    release_threshold: 0.85  # Aumentato
    defrag_threshold: 0.75  # Aumentato
    periodic_gc: true
    gc_interval: 30  # Ridotto per pulizia più frequente

  ensemble_weights:
    base_gene: 0.25
    volatility_gene: 0.3
    momentum_gene: 0.3
    pattern_gene: 0.15

  fitness_weights:
    profit_score:
      total_pnl: 0.3
      max_drawdown: 0.3
      sharpe_ratio: 0.4
    quality_score:
      win_rate: 0.4
      trade_frequency: 0.3
      consistency: 0.3
    final_weights:
      profit: 0.45
      quality: 0.4
      diversity: 0.15
    penalties:
      max_trades:
        limit: 400
        penalty: 0.7
      max_drawdown:
        limit: 0.25
        penalty: 0.8
      min_win_rate:
        limit: 0.45
        penalty: 0.95

download:
  symbol: "BTCUSDT"
  interval: "1m"
  start_date: "2023-06-01"
  end_date: null
  batch_size: 1000
  output_folder: "data"
  api:
    key: ""
    secret: ""
